### ISSUE TITLE
Error for 2D images when running inside Docker container for linux requirements.

### ISSUE THREAD

**Issue by KartikeyKansal1** [AllenCellModeling/cyto-dl#335]
Hey, I've been able to successfully run cyto-dl locally on my Mac inside a conda environment. I'm trying to run it on a High Throughput Computing cluster for which I am required to use Docker containers. I keep running into the same error even when I created a conda environment inside my container.
**The docker works for the example data with the default configurations but fails to do so for 2D images.**

```
[2024-02-19 23:43:07,313][__main__][INFO] - Instantiating data <cyto_dl.datamodules.dataframe.DataframeDatamodule>
[2024-02-19 23:43:11,086][cyto_dl.utils.template_utils][ERROR] - 
Traceback (most recent call last):
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/dataframe_datamodule.py", line 104, in __init__
    self.datasets = make_multiple_dataframe_splits(
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/utils.py", line 221, in make_multiple_dataframe_splits
    split = get_canonical_split_name(split)
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/utils.py", line 154, in get_canonical_split_name
    raise ValueError
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 53, in wrap
    out = task_func(cfg=cfg)
  File "/CytoDL_Template_Staging_240216/cyto-dl/cyto_dl/train.py", line 49, in train
    data = hydra.utils.instantiate(cfg.data)
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/opt/conda/envs/myenv1-240219/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'cyto_dl.datamodules.dataframe.dataframe_datamodule.DataframeDatamodule':
ValueError()
full_key: data
[2024-02-19 23:43:11,087][cyto_dl.utils.template_utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=im2im/labelfree.yaml', 'trainer=cpu', 'experiment_name=chtc-example1', 'run_name=train-run1']
Error in call to target 'cyto_dl.datamodules.dataframe.dataframe_datamodule.DataframeDatamodule':
ValueError()
full_key: data
```
Any suggestions to resolve this?

**Comment by benjijamorris** [comment]
It looks like you might have some `.csv` files besides `train`/`test`/`valid.csv` in your data path, if that's the case does deleting those help?

**Comment by KartikeyKansal1** [comment]
I had some other csv files in my data path but the error still pertains even after removing those. It's working fine in a conda environment locally on my machine.

**Comment by KartikeyKansal1** [comment]
Hi @benjijamorris, any further suggestions? having other csv files is not the problem as it runs successfully locally on my machine. This seems to be only an issue when run inside a docker container.

**Comment by benjijamorris** [comment]
Hi @KartikeyKansal1! One alternative is to point your `data.path` directly to your csv (instead of the directory). To do this, you'll need to add a column in your csv called `split` that has the value `test` in every row. under data, you'll also need to include `split` in the `data.columns` list and set `data.split_column=split`. Let me know if this works for you!

**Comment by KartikeyKansal1** [comment]
It currently points to the labelfree directory which has 3 csv files - train/test/valid.csv. So I'm a little confused here whether you want me to point it to only train.csv? and add a third column split after brightfield and signal?

Should I combine the three in a single csv file with split column values as train/test/valid accordingly?

**Comment by benjijamorris** [comment]
Sorry, are you trying to train or run inference? If train, you can create one .csv file with the split column labeled one of `train`/`test`/`valid` and point to that file.

**Comment by KartikeyKansal1** [comment]
Getting this error now:

```
[2024-02-22 19:31:47,547][cyto_dl.utils.template_utils][ERROR] - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/utility/dictionary.py", line 266, in __call__
    d[key] = self.adjuster(d[key], meta_dict)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/utility/array.py", line 204, in __call__
    img = MetaTensor(img)
  File "/usr/local/lib/python3.10/site-packages/monai/data/meta_tensor.py", line 116, in __new__
    return torch.as_tensor(x, *args, **_kwargs).as_subclass(cls)
TypeError: new(): invalid data type 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 53, in wrap
    out = task_func(cfg=cfg)
  File "/CytoDL_Template_Staging_240222/cyto-dl/cyto_dl/train.py", line 88, in train
    trainer.fit(model=model, datamodule=data, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 108, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 126, in __next__
    batch = super().__next__()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 58, in __next__
    batch = next(self.iterator)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 285, in __next__
    out = next(self._iterator)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 123, in __next__
    out = next(self.iterators[0])
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 298, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 418, in _transform
    pre_random_item = self._cachecheck(self.data[index])
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 391, in _cachecheck
    _item_transformed = self._pre_transform(deepcopy(item_transformed))  # keep the original hashed
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 332, in _pre_transform
    item_transformed = self.transform(item_transformed, end=first_random, threading=True)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.utility.dictionary.EnsureChannelFirstd object at 0x7f6ba3299420>
[2024-02-22 19:31:47,563][cyto_dl.utils.template_utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=im2im/labelfree.yaml', 'trainer=cpu', 'experiment_name=chtc-example1', 'run_name=train-run1']
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/utility/dictionary.py", line 266, in __call__
    d[key] = self.adjuster(d[key], meta_dict)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/utility/array.py", line 204, in __call__
    img = MetaTensor(img)
  File "/usr/local/lib/python3.10/site-packages/monai/data/meta_tensor.py", line 116, in __new__
    return torch.as_tensor(x, *args, **_kwargs).as_subclass(cls)
TypeError: new(): invalid data type 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/CytoDL_Template_Staging_240222/cyto-dl/cyto_dl/train.py", line 133, in main
    metric_dict, _ = train(cfg)
  File "/usr/local/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 56, in wrap
    raise ex
  File "/usr/local/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 53, in wrap
    out = task_func(cfg=cfg)
  File "/CytoDL_Template_Staging_240222/cyto-dl/cyto_dl/train.py", line 88, in train
    trainer.fit(model=model, datamodule=data, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 108, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 126, in __next__
    batch = super().__next__()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 58, in __next__
    batch = next(self.iterator)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 285, in __next__
    out = next(self._iterator)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 123, in __next__
    out = next(self.iterators[0])
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 298, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 418, in _transform
    pre_random_item = self._cachecheck(self.data[index])
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 391, in _cachecheck
    _item_transformed = self._pre_transform(deepcopy(item_transformed))  # keep the original hashed
  File "/usr/local/lib/python3.10/site-packages/monai/data/dataset.py", line 332, in _pre_transform
    item_transformed = self.transform(item_transformed, end=first_random, threading=True)
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/usr/local/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.utility.dictionary.EnsureChannelFirstd object at 0x7f6ba3299420>
```

**Comment by benjijamorris** [comment]
Which config is this for? It looks like this is trying to add a channel to a string (instead of a loaded image tensor). If you check the transforms you're applying, are all the images you want to work with being loaded?

**Comment by KartikeyKansal1** [comment]
This is for labelfree training on 2D images. I'm running using the default model configurations for 2D images. 
My csv file looks like this:
<img width="494" alt="image" src="https://github.com/AllenCellModeling/cyto-dl/assets/56447914/24b5be9d-ebbd-4bab-88fc-fc61907bac14">

Did you mean to have a csv which links to 3 separate csv (train/test/val)?

Can you guide me on how to check if the images I'm working with are being loaded?

**Comment by benjijamorris** [comment]
I would check:
1. Do you have an image loading transform for you brightfield and signal columns?
2. If you have `persist_cache: True` in your experiment config, try deleting the cache directory
3. Insert monai's [DataStatsD](https://docs.monai.io/en/stable/transforms.html) transform to examine what your data looks like right before the transform causing the issue to make sure your data look how you expect

If you're using the defaults without any modifications, it will try to load the 5th/6th channel from your source/target data (see [here](https://github.com/AllenCellModeling/cyto-dl/blob/2b89383bac7cf41e62703ea4d7dd697b2c16fcd4/configs/data/im2im/labelfree.yaml#L25)). I'd expect this to crash if your data does not have this many channels, but this might cause issues.

**Comment by KartikeyKansal1** [comment]
Hi @benjijamorris, let me reiterate the complete issue:
1. I have image loading transforms
2. persist_cache is False and I tried after deleting cache directory as well, didn't help.

I have the configurations for a training on 2D images, so it's loading the relevant channels and **it's working perfectly locally on my mac in a conda environment.** 

Now I'm trying to run this on a High Throughput Computing cluster. I get the following error when I do it on the distributed computational resources: 

```
[2024-02-26 11:02:18,344][__main__][INFO] - Instantiating data <cyto_dl.datamodules.dataframe.DataframeDatamodule>
[2024-02-26 11:02:21,687][cyto_dl.utils.template_utils][ERROR] - 
Traceback (most recent call last):
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/dataframe_datamodule.py", line 104, in __init__
    self.datasets = make_multiple_dataframe_splits(
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/utils.py", line 221, in make_multiple_dataframe_splits
    split = get_canonical_split_name(split)
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/cyto_dl/datamodules/dataframe/utils.py", line 154, in get_canonical_split_name
    raise ValueError
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 53, in wrap
    out = task_func(cfg=cfg)
  File "/var/lib/condor/execute/slot3/dir_132001/CytoDL_Template_Staging_240223/cyto-dl/cyto_dl/train.py", line 49, in train
    data = hydra.utils.instantiate(cfg.data)
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/var/lib/condor/execute/slot3/dir_132001/env-exp1-240223/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'cyto_dl.datamodules.dataframe.dataframe_datamodule.DataframeDatamodule':
ValueError()
full_key: data
[2024-02-26 11:02:21,688][cyto_dl.utils.template_utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=im2im/labelfree.yaml', 'trainer=cpu', 'experiment_name=chtc-example1', 'run_name=train-run1']
Error in call to target 'cyto_dl.datamodules.dataframe.dataframe_datamodule.DataframeDatamodule':
ValueError()
full_key: data
```
**I get this exact same error when I run inside a docker container** :which makes me think running  inside docker or on the distributed computational resource is interfering with access to data?

3. I added Monai's DataStatsd but still got the same error as above.
I can see Data Statistics though if I run it locally in a conda environment (screenshot below) which implies that the data isn't being loaded in docker or distributed computational resources. 
<img width="823" alt="image" src="https://github.com/AllenCellModeling/cyto-dl/assets/56447914/c79a2edf-fa09-42aa-a315-fd956215b98b">

**Comment by benjijamorris** [comment]
Got it. I'll add this to my list of development items, but it may be a while.

**Comment by KartikeyKansal1** [comment]
Thanks for taking a note. 
This is specifically an issue with 2D images, as the training runs successfully  when I do for the example data set : both on docker and on distributed computational resource.

**Comment by benjijamorris** [comment]
Awesome! If you'd like to make a PR I'd be happy to incorporate this. Nice find 👍
