### ISSUE TITLE
Write test for merging transform

### ISSUE THREAD

**Issue by benjijamorris** [AllenCellModeling/cyto-dl#363]
- test with example experiment data with `missing_key_mode=create`

**Comment by benjijamorris** [comment]
Traceback (most recent call last):
  File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/cyto_dl/image/transforms/multiscale_cropper.py", line 144, in __call__
    slices = self.generate_slices({k: image_dict[k] for k in available_keys})
  File "/Users/brian.kim/anaconda3/envs/ml-seg/lib/python3.10/site-packages/cyto_dl/image/transforms/multiscale_cropper.py", line 144, in <dictcomp>
    slices = self.generate_slices({k: image_dict[k] for k in available_keys})
KeyError: 'target'

**Comment by yrkim98** [comment]
To replicate my issue with segmenter:

- Using `segmentation_plugin.yaml`
- Changed all missing_key_mode’s in /data/im2im/segmentation_plugin.yaml to “create" instead of “ignore"
- Running training with example_experiment_data from cyto-dl
- CSV contaings `raw`, `seg1`, `seg2`, `exclude_mask`, `base_image`, `merge_mask` columns

More info at https://alleninstitute.atlassian.net/wiki/spaces/SF/pages/184549397/Current+cyto-dl+issues+with+ml-segmenter under **Training is not working using the sementation_plugin config** -> **Merged transform not working with the fixes on cyto-dl branch**
