### ISSUE TITLE
Multi-channel input to single-channel output

### ISSUE THREAD

**Issue by KartikeyKansal1** [AllenCellModeling/cyto-dl#368]
I am running python cyto_dl/train.py experiment=im2im/labelfree.yaml. I have changed the configurations for 2 channel input but keep running into this error.

Is there a way to specify the return_dims?

```
`Traceback (most recent call last):
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/io/array.py", line 282, in __call__
    img_array, meta_data = reader.get_data(img)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/cyto_dl/image/io/monai_bio_reader.py", line 36, in get_data
    data = img_obj.get_image_dask_data(**self.reader_kwargs).compute()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/aicsimageio/aics_image.py", line 649, in get_image_dask_data
    return transforms.reshape_data(
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/aicsimageio/transforms.py", line 183, in reshape_data
    raise ConflictingArgumentsError(
aicsimageio.exceptions.ConflictingArgumentsError: When selecting a multiple dimension indices, the specified dimension must be provided in return_dims. return_dims=ZYX, dimension C = [0, 1]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/cyto_dl/utils/template_utils.py", line 53, in wrap
    out = task_func(cfg=cfg)
  File "/Users/kartikeykansal/Documents/tensionGAN/Local Conda experiments/240322/Experiment 1/cyto-dl-staging-240321/cyto_dl/train.py", line 88, in train
    trainer.fit(model=model, datamodule=data, ckpt_path=cfg.get("ckpt_path"))
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 108, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 126, in __next__
    batch = super().__next__()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 58, in __next__
    batch = next(self.iterator)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 285, in __next__
    out = next(self._iterator)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 123, in __next__
    out = next(self.iterators[0])
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 298, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/data/dataset.py", line 418, in _transform
    pre_random_item = self._cachecheck(self.data[index])
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/data/dataset.py", line 391, in _cachecheck
    _item_transformed = self._pre_transform(deepcopy(item_transformed))  # keep the original hashed
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/data/dataset.py", line 332, in _pre_transform
    item_transformed = self.transform(item_transformed, end=first_random, threading=True)
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/Users/kartikeykansal/miniconda3/envs/cytoenv240131/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f814a24d390>
```

_Originally posted by @KartikeyKansal1 in https://github.com/AllenCellModeling/cyto-dl/discussions/358#discussioncomment-8913942_

**Comment by benjijamorris** [comment]
Yep! setting `dimension_order_out: CZYX` under the `cyto_dl.image.io.MonaiBioReader` should do it!

**Comment by KartikeyKansal1** [comment]
Hi @benjijamorris , I'm still figuring out how to do a multi channel input to a single channel output. To me it seems that my configuration settings are correct but I might be wrong. Can you help me point out if I'm missing out any configuration changes. I have my input image in the source column which is a 2 channel image. And target column has a 1 channel image.

spatial_dims=3, raw_im_channels=2

for source column: 
dimension_order_out: CZYX
channel_dim=-1

for target column: 
dimension_order_out: YX

I'm getting the following error currently which looks like I'm not the dimensions in correct order.
ValueError: Crop size [32 32] is too large for image size [ 1 96]

Input image's info: it's a 2 channel 96x96 image
<img width="358" alt="image" src="https://github.com/AllenCellModeling/cyto-dl/assets/56447914/b42323ba-27da-45c6-a48d-af8032667255">
